version: '2'
services:
  w3rpa-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    container_name: w3rpa-mysql
    image: w3rpa-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306

  w3rpa-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    hostname: w3rpa-redis
    container_name: w3rpa-redis

  w3rpa-server:
    build:
      context: ./rpa-server/rpa-server-start
    restart: on-failure
    depends_on:
      - w3rpa-mysql
      - w3rpa-redis
    container_name: w3rpa-server
    image: w3rpa-server
    hostname: w3rpa-server
    ports:
      - 8080:8080